### ISSUE TITLE
Issues with Emoji.

### ISSUE THREAD

**Issue by shalecraig** [geelen/typeslab#4]
Typeslab won't render the coffee icon in this this entry:

wake up
and rdrink a
morning
coffee☕️
you can
sleep
when you are
dead

**Comment by ErtugKaya** [comment]
That coffee icon is not a part of the font, but a bitmap. 

To support icons, @geelen  should include a proper font, like [font awesome](http://fortawesome.github.io/Font-Awesome/icon/coffee/) and a way to switch to it.

**Comment by geelen** [comment]
Emoji support is really flaky, yeah. Initially it was working in Chrome on OSX 10.10.3 but now it isn't. It does work on Firefox:

![image](https://cloud.githubusercontent.com/assets/23264/7152408/06d88856-e36e-11e4-8137-28f42e2362ef.png)

Gonna close this for now because I don't have time to actually investigate why rendering emoji to canvas is so flaky. Also, I'm not going to add icon fonts or user-defined fonts, that's not the point. Embrace constraints & use ASCII art :)

![image](https://cloud.githubusercontent.com/assets/23264/7152440/9828820c-e36e-11e4-840d-5f63f72f99f7.png)
